#!/bin/zsh
# Generate PKHeX.Mac/Services/TypeIconData.g.cs from the MIT-licensed
# partywhale/pokemon-type-icons SVG set.
#
# Avalonia has no built-in SVG renderer and no SVG->PNG tool is assumed present,
# so the icons are transcoded into path geometry the app draws natively. That keeps
# them vector-crisp at any size with no extra NuGet dependency.
#
# Source: https://github.com/partywhale/pokemon-type-icons (MIT)
set -euo pipefail
cd "$(dirname "$0")/.."

BASE="https://raw.githubusercontent.com/partywhale/pokemon-type-icons/main/icons"
OUT="PKHeX.Mac/Services/TypeIconData.g.cs"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Order matters: index = PKHeX's internal type id.
TYPES=(normal fighting flying poison ground rock bug ghost steel fire water grass electric psychic ice dragon dark fairy)

echo "==> Downloading ${#TYPES[@]} type icons..."
for t in $TYPES; do
  curl -sfL "$BASE/$t.svg" -o "$TMP/$t.svg"
done

echo "==> Transcoding to Avalonia geometry..."
python3 - "$TMP" "$OUT" "${TYPES[@]}" <<'PY'
import re, sys, os

tmp, out = sys.argv[1], sys.argv[2]
types = sys.argv[3:]

def parse(path):
    """Return [(fill, path_data), ...] in document order."""
    svg = open(path).read()

    # Class -> fill colour, from the embedded <style> block.
    classes = dict(re.findall(r'\.(cls-\d+)\s*\{\s*fill:\s*(#[0-9a-fA-F]{3,6});', svg))

    def fill_of(tag):
        m = re.search(r'class="([^"]+)"', tag)
        if m and m.group(1) in classes:
            return classes[m.group(1)]
        m = re.search(r'fill="(#[0-9a-fA-F]{3,6})"', tag)
        return m.group(1) if m else "#ffffff"

    shapes = []
    for tag in re.findall(r'<(?:circle|path|ellipse)\b[^>]*/?>', svg):
        fill = fill_of(tag)
        if tag.startswith('<circle'):
            cx = float(re.search(r'cx="([-\d.]+)"', tag).group(1))
            cy = float(re.search(r'cy="([-\d.]+)"', tag).group(1))
            r = float(re.search(r'r="([-\d.]+)"', tag).group(1))
            # Two arcs make a full circle in path form.
            d = (f"M{cx - r},{cy} A{r},{r} 0 1,0 {cx + r},{cy} "
                 f"A{r},{r} 0 1,0 {cx - r},{cy} Z")
            shapes.append((fill, d))
        elif tag.startswith('<ellipse'):
            cx = float(re.search(r'cx="([-\d.]+)"', tag).group(1))
            cy = float(re.search(r'cy="([-\d.]+)"', tag).group(1))
            rx = float(re.search(r'rx="([-\d.]+)"', tag).group(1))
            ry = float(re.search(r'ry="([-\d.]+)"', tag).group(1))
            d = (f"M{cx - rx},{cy} A{rx},{ry} 0 1,0 {cx + rx},{cy} "
                 f"A{rx},{ry} 0 1,0 {cx - rx},{cy} Z")
            shapes.append((fill, d))
        else:
            m = re.search(r'\bd="([^"]+)"', tag)
            if m:
                shapes.append((fill, " ".join(m.group(1).split())))
    return shapes

lines = [
    "// <auto-generated>",
    "//     Generated by scripts/fetch-type-icons.sh — do not edit by hand.",
    "//     Geometry transcoded from https://github.com/partywhale/pokemon-type-icons (MIT).",
    "// </auto-generated>",
    "",
    "namespace PKHeX.Mac.Services;",
    "",
    "/// <summary>Path geometry for the 18 type symbol icons, on a 256x256 canvas.</summary>",
    "internal static class TypeIconData",
    "{",
    "    /// <summary>Indexed by PKHeX's internal type id; each entry is drawn in order.</summary>",
    "    internal static readonly (string Fill, string Data)[][] Shapes =",
    "    [",
]
for t in types:
    shapes = parse(f"{tmp}/{t}.svg")
    lines.append(f"        // {t}")
    lines.append("        [")
    for fill, d in shapes:
        esc = d.replace('"', '\\"')
        lines.append(f'            ("{fill}", "{esc}"),')
    lines.append("        ],")
lines += ["    ];", "}", ""]

os.makedirs(os.path.dirname(out), exist_ok=True)
open(out, "w").write("\n".join(lines))
print(f"wrote {out} ({os.path.getsize(out)//1024} KB) for {len(types)} types")
PY
